### ISSUE TITLE
Upgrade kind version

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-release-tools#101]
Our release-1.19 and master CI jobs are failing because they can't build kind images. 

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-csi-1-19-on-kubernetes-1-19/1309506163229855744/build-log.txt
```
Building node image in: /tmp/kind-node-image746303175
ERROR: error building node image: failed to copy build artifact: lstat /home/prow/go/pkg/csiprow.RySNwxo32r/src/kubernetes/bazel-bin/cmd/kubeadm/linux_amd64_stripped/kubeadm: no such file or directory
ERROR: 'kind build node-image' failed
```

**Comment by msau42** [comment]
@pohly would you be able to help take a look at this?

**Comment by pohly** [comment]
Solved via PR #107 

/close

**Comment by pohly** [comment]
/reopen

Still need to update csi-release-tools in the different components.

**Comment by pohly** [comment]
/close

It was resolved.
