### ISSUE TITLE
Multi-arch builds are failing

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-release-tools#105]
We successfully built amd64, but ppc64le is failing:

```
 > [1/2] FROM gcr.io/distroless/static:latest:

failed to solve: rpc error: code = Unknown desc = failed to load cache key: no match for platform in manifest sha256:7d687a1d8809b89c60211ff08a9277ffbe76895907aedffac4d2400a4e1a2dc7: not found
+ docker buildx rm multiarchimage-buildertest
make: *** [release-tools/build.make:128: push-multiarch-csi-provisioner] Error 1
ERROR
ERROR: build step 0 "gcr.io/k8s-testimages/gcb-docker-gcloud:v20200421-a2bf5f8" failed: step exited with non-zero status: 2
```

**Comment by msau42** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/post-external-provisioner-push-images/1312087665054584832/build-log.txt

**Comment by msau42** [comment]
This may be related to changes made for:
https://github.com/GoogleContainerTools/distroless/issues/583

**Comment by namrata-ibm** [comment]
@msau42 It does seem to be breaking since above change. The latest [gcr.io/distroless/static](https://console.cloud.google.com/gcr/images/distroless/GLOBAL/static?gcrImageListsize=30) image shows only amd and arm manifest. Pulling this image gives same error on s390x machine as seen in the Prow job.
We would need to extend support for ppc64le+s390x in distroless image.

**Comment by msau42** [comment]
@namrata-ibm would you be able to help with adding support for those other platforms to the distroless build?

**Comment by namrata-ibm** [comment]
@msau42 Adding support to distroless would need some time to sort Bazel related support first. Will work on that as a long term solution in parallel. 
However to get the builds passing again, can we make changes to Dockerfile to use `gcr.io/distroless/static:latest-amd64` image as suggested [here](https://github.com/GoogleContainerTools/distroless/issues/583#issuecomment-704281366)? I can raise PRs for that.
cc @pohly

**Comment by msau42** [comment]
Yes, the workaround sounds fine to me. I'm only concerned that we will stop getting updates to the image so we should actively work on adding support for the missing platforms

**Comment by stuartpb** [comment]
This workaround is no good - switching the build to amd64 just broke all the pods running on my arm64 nodes.

**Comment by pohly** [comment]
@stuartpb can you be more specific? Which containers broke (name, image version, etc.) and which binary in them cannot be executed?

**Comment by stuartpb** [comment]
These were the images I saw exec format errors from - I believe it was in every container spawned by Rook using any one of them:

```
k8s.gcr.io/sig-storage/csi-provisioner:v1.6.0
k8s.gcr.io/sig-storage/csi-snapshotter:v2.1.1
k8s.gcr.io/sig-storage/csi-attacher:v2.2.0
k8s.gcr.io/sig-storage/csi-resizer:v0.4.0
```

**Comment by msau42** [comment]
We have not officially supported multi arch images for those versions.

Multi arch is supported starting with
provisioner 2.0
attacher 3.0
snapshotter 3.0
resizer 1.0

**Comment by stuartpb** [comment]
Maybe it's a coincidence, then, but I'm pretty sure I was using those images successfully for about a week at least before this change hit.

**Comment by dims** [comment]
@msau42 https://github.com/GoogleContainerTools/distroless/pull/622

**Comment by msau42** [comment]
This should be addressed with the latest sidecar releases and head.

/lclose
