### ISSUE TITLE
prow.sh doesn't error check GOPATH

### ISSUE THREAD

**Issue by bswartz** [kubernetes-csi/csi-release-tools#142]
If GOPATH is undefined, prow.sh attempts to create directories in the root of the filesystem instead of exiting with an error.

```
$ make
./release-tools/verify-go-version.sh "go"
mkdir: cannot create directory ‘/pkg’: Permission denied
mkdir: cannot create directory ‘/artifacts’: Permission denied
```

**Comment by pohly** [comment]
This is a bit more complicated: when sourcing `prow.sh` to get settings out of it, it already sets up some paths. This litters `$GOPATH/pkg` with `csiprow.*` directories even when not actually running any tests.

It would be nicer to move those `mktemp` and `mkdir` invocations to a setup function. I'll check...

/assign

**Comment by pohly** [comment]
Potential fix is being tested in https://github.com/kubernetes-csi/csi-driver-host-path/pull/278
