### ISSUE TITLE
all csi repo image build pipelines are broken now due to golang binary download failure

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/csi-release-tools#245]
e.g. in following golang binary path, `https://dl.google.com/go/go1.21.3.linux-amd64.tar.gz` is the right path, release-tools are missing patch version, it now fails here:
https://github.com/kubernetes-csi/csi-release-tools/blob/267b40e9756ea785b6ff79bea19174174ea9585c/prow.sh#L437

how can I fix this issue? @pohly 

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/canary-external-snapshotter-push-images/1734355030900740096
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-csi-driver-host-path-push-images/1735030620733575168
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-csi-driver-smb-push-images/1735616921413357568

```
Setting /usr/bin/qemu-hexagon-static as binfmt interpreter for hexagon
Mon Dec 11 23:32:17 UTC 2023 go1.20.5 $ curl --fail --location https://dl.google.com/go/go1.21.linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  1449    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
tar: invalid magic
tar: short read
ERROR: installation of Go 1.21 failed
ERROR
ERROR: build step 0 "gcr.io/k8s-testimages/gcb-docker-gcloud:v20[230](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/canary-external-snapshotter-push-images/1734355030900740096#1:build-log.txt%3A230)623-56e06d7c18" failed: step exited with non-zero status: 1
```

**Comment by andyzhangx** [comment]
/assign @pohly
cc @msau42

**Comment by andyzhangx** [comment]
cc @xing-yang

**Comment by mauriciopoppe** [comment]
The path in `curl --fail --location https://dl.google.com/go/go1.21.linux-amd64.tar.gz` is invalid, I think this line https://github.com/kubernetes-csi/csi-release-tools/blob/267b40e9756ea785b6ff79bea19174174ea9585c/prow.sh#L89 should be 1.21.3

**Comment by xing-yang** [comment]
Should we update this to 1.21.5?
https://github.com/kubernetes/kubernetes/pull/122201/files#diff-69c69535f549f1e70ce037415e46a2894f04d4147c7929de6ef1db8f72a0a136R1

**Comment by andyzhangx** [comment]
thanks, issue is fixed, I  will update release-tools in all repos to adopt the fix.
