### ISSUE TITLE
Deprecation warning on registry v2 schema1 support on quay

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/csi-release-tools#37]
While pushing a testing image for snapshot beta to quay, I got a warning message: "[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption."

CC: @pohly @msau42

**Comment by pohly** [comment]
The warning was from `docker push`? I would hope that the `quay.io` admins are aware of this.

Besides that, our solution would be to not use quay.io anymore. If it really fails to work (which I find unlikely), we just need to get off it quickly enough.

**Comment by xing-yang** [comment]
Yes, this is from ```docker push```.

**Comment by msau42** [comment]
Now that we're publishing our images to gcr.io, I don't think this is an issue anymore
/close
