### ISSUE TITLE
Add mdl, yaml linter..etc to the repo 

### ISSUE THREAD

**Issue by humblec** [kubernetes-csi/csi-release-tools#85]
We should have more static check to catch most of the errors like linter, markdown..etc. This issue will keep track of the same.

**Comment by humblec** [comment]
/assign @humblec 

@pohly please let me know if you have any any other things on your mind which could help ?

**Comment by humblec** [comment]
> /assign @humblec
> 
> @pohly please let me know if you have any other things on your mind which could help with this area ?

**Comment by pohly** [comment]
A single issue per proposed linter would be simpler to track.

For each linter, we need to decide whether the errors that it finds are worth the limitations (whatever they may be - depends on how strict linting is).
