### ISSUE TITLE
Moving images away from quay.io?

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/csi-release-tools#86]
CI is failing because quay.io is down.  It's reported in this issue:
https://github.com/kubernetes/kubernetes/issues/91242

Should we move our images to a different repo, i.e., the community infra?

CC @msau42 @pohly

**Comment by xing-yang** [comment]
One update from https://status.quay.io/ says that "The number of open connections to the Quay.io database increased significantly causing an outage of the service, we are still investigating the root cause of this spike in DB connections. "

**Comment by xing-yang** [comment]
We have staging repos for CSI in GCR and the image promotion process.  It's used for node-driver-registrar only right now.  Should we do this for all sidecar repos?
https://github.com/kubernetes-csi/node-driver-registrar/blob/master/cloudbuild.yaml

**Comment by justaugustus** [comment]
Thanks for opening this, @xing-yang!
I poked @hasheddan to get the conversation started in https://github.com/kubernetes/kubernetes/issues/91242 / https://kubernetes.slack.com/archives/CJH2GBF7Y/p1589887799251500.

Where possible, images that are used by that community should be on community infra.
I'd suggest moving anything currently hosted at quay.io/k8scsi be moved in a CSI staging repository and then promoted to our prod registry.

Let me know how I can help and feel free to assign me in reviews. :)

**Comment by xing-yang** [comment]
Thanks @justaugustus!

**Comment by pohly** [comment]
Work is in progress. It's not just about pushing to some other registry, but also about using an entirely different build infrastructure and producing images for multiple different architectures, ideally including Windows.

As a next step it would help if someone could approve https://github.com/kubernetes-csi/node-driver-registrar/pull/82. As I said in the review of that PR, we need to figure out how building of Windows images can be unified with the approach taken for all other platforms (i.e. build the binary inside the multi-stage Dockerfile, using the same base images if possible).

/cc @vitt-bagal @jingxu97 @ddebroy

**Comment by pohly** [comment]
Previous PRs:
- https://github.com/kubernetes-csi/node-driver-registrar/pull/68
- https://github.com/kubernetes-csi/node-driver-registrar/pull/72

**Comment by pohly** [comment]
Tentative plan:
- [ ] try out cloud build one last time after merging https://github.com/kubernetes-csi/node-driver-registrar/pull/84
- [ ] move common code and files into `csi-release-tools`
- [ ] update node-driver-registrar with that
- [ ] promote multi-arch node-driver-registrar:canary image to from staging repo to final repo as a test
- [ ] update all repos with newest `csi-release-tools` *and* `ARG binary` in their Dockerfile(s)
- [ ] create build jobs similar to https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/k8s-staging-csi.yaml (ideally, through the generator script instead of manually...)

**Comment by pohly** [comment]
The vanity domain switch has completed: https://groups.google.com/forum/#!msg/kubernetes-dev/Z-y1EK-XBQM/-fehCfLpAAAJ

**Comment by pohly** [comment]
k8s.gcr.io works for "docker pull" but only redirects to https://cloud.google.com/container-registry/ when used in a web browser. To list images, use https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/sig-storage

**Comment by jingxu97** [comment]
@pohly for the multi-arch image of node-driver-registar, when can it be promoted from staging to release? https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/GLOBAL/csi-node-driver-registrar?gcrImageListsize=30

**Comment by pohly** [comment]
node-driver-registrar needs a formal new release. We don't promote rc or canary images to the production repo. According to https://github.com/orgs/kubernetes-csi/projects/29#card-42709613, it's "not ready".

**Comment by msau42** [comment]
I believe the last thing that's still remaining is to turn down our travis jobs that push to quay. I think we can do this once those minor versions are out of our support window.

**Comment by xing-yang** [comment]
@msau42 @pohly do we still need to keep this issue open?

**Comment by msau42** [comment]
Yes travis jobs are disabled, so I think we're done here.

/close
